./target/release/main -o high.toml locations/glitch_test_1.toml
./target/release/main -o high.toml locations/glitch_test_2.toml
./target/release/main -o high.toml locations/glitch_test_3.toml
./target/release/main -o high.toml locations/glitch_test_4.toml
./target/release/main -o high.toml locations/glitch_test_5.toml
./target/release/main -o high.toml locations/glitch_test_6.toml

./target/release/main -o high.toml locations/1e14.toml
./target/release/main -o high.toml locations/11_dimensions.toml
./target/release/main -o high.toml locations/e10000.toml
./target/release/main -o high.toml locations/flake.toml
./target/release/main -o high.toml locations/floral_fantasy.toml
./target/release/main -o high.toml locations/golden_spider.toml
./target/release/main -o high.toml locations/long.toml
./target/release/main -o high.toml locations/lya.toml
./target/release/main -o high.toml locations/opus.toml
./target/release/main -o high.toml locations/peanuts.toml
./target/release/main -o high.toml locations/wfs.toml
./target/release/main -o high.toml locations/x.toml